import { ThemeToggle } from "@/components/theme-toggle";
import { NewsFeed } from "@/components/news-feed";

export const dynamic = "force-dynamic";

function SignalMark() {
  return <span className="flex h-8 w-8 items-center justify-center border border-[var(--cyan)] text-[var(--cyan)] shadow-[0_0_18px_rgba(69,244,209,0.25)]"><span className="h-2 w-2 rotate-45 bg-[var(--cyan)]" /></span>;
}

export default function Home() {
  return <div className="signal-grid relative min-h-screen overflow-hidden bg-[var(--background)]"><div className="scanlines absolute inset-0 z-0 opacity-50" /><header className="relative z-10 border-b border-[var(--line)] bg-[var(--background)]/90 backdrop-blur-md"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-6 px-5 py-4 lg:px-8"><div className="flex items-center gap-3"><SignalMark /><div><p className="font-mono text-sm font-bold tracking-[0.2em] text-[var(--foreground)]">SIGNAL</p><p className="font-mono text-[9px] tracking-[0.16em] text-[var(--muted)]">TECH INTELLIGENCE / LIVE</p></div></div><div className="hidden items-center gap-5 font-mono text-[10px] uppercase tracking-[0.18em] text-[var(--muted)] md:flex"><span className="flex items-center gap-2"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-[var(--cyan)]" />Database feed</span><span>Real sources only</span></div><div className="flex items-center gap-2"><ThemeToggle /><a className="focus-ring hidden border border-[var(--line)] px-3 py-2 font-mono text-[10px] uppercase tracking-[0.15em] text-[var(--muted)] transition hover:border-[var(--cyan)] hover:text-[var(--cyan)] sm:block" href="https://github.com/AntonyMittul/Tech_News" target="_blank" rel="noreferrer">[ source ]</a></div></div></header><main className="relative z-10 mx-auto max-w-[1500px] px-5 py-8 lg:px-8 lg:py-12"><section className="mb-10 flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="mb-4 font-mono text-xs uppercase tracking-[0.26em] text-[var(--cyan)]">{"// curated intelligence feed"}</p><h1 className="text-glow max-w-4xl text-4xl font-bold leading-[0.98] tracking-[-0.05em] text-[var(--foreground)] sm:text-6xl lg:text-7xl">The signal beneath<br /><span className="text-[var(--cyan)]">the noise.</span></h1><p className="mt-5 max-w-xl text-sm leading-7 text-[var(--muted)] sm:text-base">Real technology news collected from configured sources and stored locally for a focused reading experience.</p></div><div className="w-full max-w-sm border border-[var(--line)] bg-[var(--panel)] p-4 panel-glow"><div className="mb-3 flex items-center justify-between font-mono text-[10px] uppercase tracking-[0.16em] text-[var(--muted)]"><span>Live feed</span><span className="text-[var(--cyan)]">SOURCE LINKED</span></div><div className="h-1 bg-[var(--panel-raised)]"><div className="h-full w-full bg-[var(--cyan)] shadow-[0_0_12px_var(--cyan)]" /></div><div className="mt-3 flex justify-between font-mono text-[10px] text-[var(--muted)]"><span>Search / filter / paginate</span><span className="text-[var(--foreground)]">Ready</span></div></div></section><NewsFeed /></main></div>;
}
